## NumPy : Practice Problems 2: Solution
Easy Questions : 5

Moderate Questions : 7

Hard Questions : 3
<hr>


### 1. Create an array and find sum of it.
Level: Easy

In [2]:
import numpy as np

In [5]:
arr = np.random.randint(1,50,(3,3))
print(arr)
a = arr.sum()
a

[[ 4 23 32]
 [ 3 15  7]
 [22 11 38]]


155

### 2. Find sin of given array.
Level: Easy


In [8]:
arr = np.random.randint(1,50,(3,3))
print(arr)
s = np.sin(arr)
s

[[11 15 45]
 [14 49 44]
 [43 14 27]]


array([[-0.99999021,  0.65028784,  0.85090352],
       [ 0.99060736, -0.95375265,  0.01770193],
       [-0.83177474,  0.99060736,  0.95637593]])

### 3. Find mean of matrix along row and column.
Level: Easy

In [10]:
arr = np.random.randint(1,50,(3,3))
print(arr)
print("row wise mean",arr.mean(axis=1))
print("column wise mean",arr.mean(axis=0))

[[41 17 37]
 [47 43 33]
 [45 23 12]]
row wise mean [31.66666667 41.         26.66666667]
column wise mean [44.33333333 27.66666667 27.33333333]


### 4. Find standard deviation of given array.
Level: Easy

In [12]:
std = np.std(arr)
std

12.096321244672737

### 5. Create a 3*3 matrix and print it's transpose matrix
Level: Easy

In [14]:
print(arr)
transpose = np.transpose(arr)
transpose

[[41 17 37]
 [47 43 33]
 [45 23 12]]


array([[41, 47, 45],
       [17, 43, 23],
       [37, 33, 12]])

### 6. Create an array of 3*3 and find index of max along both axis.

Level: Medium

In [150]:
data = np.random.randint(1,50,(3,3))
print(data)
a=data.max()
print(a)
np.where (data == a)

[[29 27 19]
 [32  1 13]
 [14 22 24]]
32


(array([1], dtype=int64), array([0], dtype=int64))

In [149]:
data = np.random.randint(1,50,(3,3))
print(data)
print(data.argmax(axis=0))
print(data.argmax(axis=1))

[[17 49 22]
 [26 37  9]
 [33 29 46]]
[2 0 2]
[1 1 2]


### 7.  find sum of two matrix.
Level: Medium

In [175]:
a =np.random.rand(3,3)
print(a)
b =np.random.randint(1,10,(4,4))
print(b)
sums =[]
for i in np.nditer(a):
    for j in np.nditer(b):
        sums.append(i+j)
print(np.array(sums).reshape(12,12))

[[0.62997388 0.82768616 0.62717145]
 [0.98775886 0.34655129 0.10046559]
 [0.8417278  0.03069933 0.14276212]]
[[2 1 9 7]
 [6 8 8 6]
 [9 4 5 2]
 [6 2 4 9]]
[[2.62997388 1.62997388 9.62997388 7.62997388 6.62997388 8.62997388
  8.62997388 6.62997388 9.62997388 4.62997388 5.62997388 2.62997388]
 [6.62997388 2.62997388 4.62997388 9.62997388 2.82768616 1.82768616
  9.82768616 7.82768616 6.82768616 8.82768616 8.82768616 6.82768616]
 [9.82768616 4.82768616 5.82768616 2.82768616 6.82768616 2.82768616
  4.82768616 9.82768616 2.62717145 1.62717145 9.62717145 7.62717145]
 [6.62717145 8.62717145 8.62717145 6.62717145 9.62717145 4.62717145
  5.62717145 2.62717145 6.62717145 2.62717145 4.62717145 9.62717145]
 [2.98775886 1.98775886 9.98775886 7.98775886 6.98775886 8.98775886
  8.98775886 6.98775886 9.98775886 4.98775886 5.98775886 2.98775886]
 [6.98775886 2.98775886 4.98775886 9.98775886 2.34655129 1.34655129
  9.34655129 7.34655129 6.34655129 8.34655129 8.34655129 6.34655129]
 [9.34655129 4.34655129 

In [176]:
a = np.array([[2,3,5],[5,8,21]])
print(a)
v = [1,2,3]
a+v

[[ 2  3  5]
 [ 5  8 21]]


array([[ 3,  5,  8],
       [ 6, 10, 24]])

### 8. Find indexes of max element along axis=0 and axis=1 .
Level: Medium

In [177]:
data = np.random.randint(1,50,(3,3))
print(data)
print(data.argmax(axis=0))
print(data.argmax(axis=1))

[[25 41 24]
 [ 8 49 17]
 [27  2 43]]
[2 1 2]
[1 1 2]


### 9. Write a program to add two arrays of different shape.
Hint: Broadcasting
Level: Medium
sample input:

a=[0.0,10.0,20.0,30.0]

b=[1.0,2.0,3.0]

output:

[[  1.,   2.,   3.],

 [ 11.,  12.,  13.],
 
 [ 21.,  22.,  23.],
 
 [ 31.,  32.,  33.]]

In [168]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis]+b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

# 10. Try to solve a array and print a array with indices which would sort the given array.

sample input:

a = [3,1,8,2]

output:

[1,3,0,2]

In [151]:
x = np.array([3,1,8,2])
np.argsort(x)

array([1, 3, 0, 2], dtype=int64)

### 11. Try to do perform same operation mentioned in previous questions for multidimentional array along both axis.

Level: Medium

In [158]:
a = np.random.randint(1,50,(3,3))
print(a)
np.argsort(a,axis=0)

[[29  7 15]
 [25  2 43]
 [18 18 11]]


array([[2, 1, 2],
       [1, 0, 0],
       [0, 2, 1]], dtype=int64)

In [178]:
x = np.random.randint(10,50,(3,3))
print("along axis 1:\n",np.argsort(x, axis=1))
print("along axis 0:\n",np.argsort(x, axis=0))

along axis 1:
 [[2 0 1]
 [1 0 2]
 [1 2 0]]
along axis 0:
 [[0 2 0]
 [2 1 2]
 [1 0 1]]


### 12. calculate multiplication of transpose and matrix itself of a 3*3 matrix.
Level: Medium

In [33]:
mat = np.random.randint(1,10,(3,3))
print(mat)
transpose = np.transpose(mat)
print(transpose)
print(np.matmul(mat,transpose))

[[4 8 2]
 [2 4 6]
 [3 7 1]]
[[4 2 3]
 [8 4 7]
 [2 6 1]]
[[84 52 70]
 [52 56 40]
 [70 40 59]]


In [180]:
a = np.random.randint(10,size=(3,3)) 
print("original matrix:\n",a)
print("Transpose of a:\n",a.T) 
print("Multiplication:\n",a*a.T)

original matrix:
 [[8 8 1]
 [3 8 0]
 [4 8 1]]
Transpose of a:
 [[8 3 4]
 [8 8 8]
 [1 0 1]]
Multiplication:
 [[64 24  4]
 [24 64  0]
 [ 4  0  1]]


### 13. Find solution for given linear equstion:

2x + 5*y = 28
4*x + 3*y = 81

Level: Hard

In [ ]:
a = np.array([[2, 5], [4, 3]])  
b = np.array([28, 81]) 
print("Solution of linear equations:", np.linalg.solve(a, b))


### 14. Find Rank, Trace, Inverse, Determinant of a given matrix.

A=[[1, 1, 1], 
              [2, 2, 2], 
              [3, 3, 3]]) 
              
Level: Hard

In [160]:
arr=np.array([[1, 4, 6], [9, 2, 8], [7, 3, 5]])
print(arr)
rank = np.linalg.matrix_rank(arr)
print("Rank :",rank)
trace = np.trace(arr)
print("Trace :",trace)
det = np.linalg.det(arr)
print(det)
print("Inverse:\n", np.linalg.inv(arr))

[[1 4 6]
 [9 2 8]
 [7 3 5]]
Rank : 3
Trace : 8
108.00000000000003
Inverse:
 [[-0.12962963 -0.01851852  0.18518519]
 [ 0.10185185 -0.34259259  0.42592593]
 [ 0.12037037  0.23148148 -0.31481481]]


### 15. Find cube of a mtrix.

Level: Hard

In [161]:
A = [[1, 4, 6], [9, 2, 8], [7, 3, 5]]

np.linalg.matrix_power(A, 3)

array([[ 825,  580, 1054],
       [1429,  790, 1560],
       [1147,  647, 1261]])