## NumPy : Practice Problems 1
Easy Questions : 7
Moderate Questions : 7
Hard Questions : 3
<hr>


### 1. Write a NumPy program to get the numpy version and show numpy build configuration.

Level: Easy

In [1]:
import numpy as np

print(np.version.version)
print(np.__config__)

1.15.4
<module 'numpy.__config__' from 'c:\\python36\\lib\\site-packages\\numpy\\__config__.py'>


### 2. Create a null vector of size 10 but the fifth value which is 1.

Level: Easy

In [2]:
ten_zeroes = np.zeros(10)
ten_zeroes[4] = 1
print(ten_zeroes)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


###  Create a vector with values ranging from 10 to 49.

Level: Easy

In [4]:
ten_fortynine = np.arange(10,50)
print(ten_fortynine)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 3. create two arrays and stack them vertically

Level: Easy

In [5]:
a = np.random.randint(10,100,(4,3))
b = np.random.randint(110,200,(4,3))

print(np.vstack([a,b]))

[[ 59  18  26]
 [ 89  17  52]
 [ 39  42  72]
 [ 83  14  55]
 [173 129 167]
 [163 186 166]
 [111 111 165]
 [163 117 124]]


### 4. Reverse a vector (first element becomes last).

Level: Easy

In [9]:
a = np.random.randint(10,100,(4,3))
print(a)
print(a[::-1])

[[29 37 83]
 [75 81 30]
 [48 49 87]
 [94 94 63]]
[[94 94 63]
 [48 49 87]
 [75 81 30]
 [29 37 83]]


### 5. Create a 3x3 matrix with values ranging from 0 to 8 

Level: Easy

In [11]:
a = np.random.randint(0,8,(3,3))
a

array([[1, 1, 3],
       [6, 5, 1],
       [5, 2, 1]])

### 6. Find indices of non-zero elements from [1,2,0,0,4,0]

Level: Easy

In [14]:
a = [1,2,0,0,4,0,2]
for value in range(0,len(a)):
    if a[value] != 0:
        print (value )

0
1
4
6


### 7. Create a 10x10 array with random values and find the minimum and maximum values.

Level: Easy

In [39]:
a = np.random.randint(1,1000,(10,10))
print(a)
minimum = min(a[0])
maximum = max(a[0])
for value in range(0,len(a)):
      
    if maximum < max(a[value]):
        maximum =  max(a[value])
    if minimum > min(a[value]):
        minimum = min(a[value])
print(maximum,minimum)



[[ 32 589 239 542 256 785 725 178 314 722]
 [ 11 600 958  42 660 898 287 558 557 119]
 [973 970 344 566 178 526 603 546 433 640]
 [611 719 544 784 240 488 892 972 750  65]
 [467 299 460  59 632  11  41 709 107 523]
 [285 281 900 147  41 247 944 265 184 599]
 [304 817 310 707 788 667 196 860 673 571]
 [253 255 115  17  66 274 569 946 909 564]
 [132  72 969 101 576 467 275 691 534 283]
 [203  24 550 432 735 684 863  77 935 352]]
973 11


### 8. Create a random vector of size 30 and find the mean value.

Level: Medium

In [46]:
a = np.random.randint(1,100,30)
print(a)
print(sum(a)/len(a))

[38 78 16 78 84 38  2 89 78 32 58 68 84 58 63 47 63 15  8 92 66 20 86 75
 25 93 77  3 40 78]
55.06666666666667


### 9. Create a 2d array with 1 on the border and 0 inside
Level: Medium

In [3]:
oneborder = np.ones((10,10))
oneborder[1:-1, 1:-1] = 0
print(oneborder)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 10. How to add a border (filled with 0's) around an existing array

Level: Medium

In [50]:
zeroborder = np.zeros((10,10))
zeroborder[1:-1,1:-1] = np.random.randint(1,1000)
print(zeroborder)

[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0. 396. 396. 396. 396. 396. 396. 396. 396.   0.]
 [  0. 396. 396. 396. 396. 396. 396. 396. 396.   0.]
 [  0. 396. 396. 396. 396. 396. 396. 396. 396.   0.]
 [  0. 396. 396. 396. 396. 396. 396. 396. 396.   0.]
 [  0. 396. 396. 396. 396. 396. 396. 396. 396.   0.]
 [  0. 396. 396. 396. 396. 396. 396. 396. 396.   0.]
 [  0. 396. 396. 396. 396. 396. 396. 396. 396.   0.]
 [  0. 396. 396. 396. 396. 396. 396. 396. 396.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]]


### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
Sample Output:
    
[[ 0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 0.  2.  0.  0.  0.]
 [ 0.  0.  3.  0.  0.]
 [ 0.  0.  0.  4.  0.]]
 
 Level: Medium

In [61]:
a = np.zeros((5,5))
for i in range(1,len(a)):
    for j in range(0,len(a[i])):
        if j == i-1:
            a[i][j] = i
print(a)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


### 12. Create a 5*5 matrix with random values and normalize it.
Level: Medium

In [62]:
m = np.random.randint(1,10,(5,5))
normalized = (m )/(np.max(m)-np.min(m))
print(m)
print(normalized)

[[5 8 4 5 2]
 [5 9 1 1 8]
 [6 3 3 7 1]
 [3 1 2 9 9]
 [6 3 1 1 9]]
[[0.625 1.    0.5   0.625 0.25 ]
 [0.625 1.125 0.125 0.125 1.   ]
 [0.75  0.375 0.375 0.875 0.125]
 [0.375 0.125 0.25  1.125 1.125]
 [0.75  0.375 0.125 0.125 1.125]]


### 13. How to find common values between two arrays
Level: Medium

In [63]:
a = np.random.randint(1,50,(4,4))
b = np.random.randint(1,50,(4,4))
print(a)
print(b)
list_a = []
list_b = []
for i in range(len(a)):
    for j in range(len(a[i])):
        list_a.append(a[i][j])
for i in range(len(b)):
    for j in range(len(b[i])):
        list_b.append(b[i][j])
set_a = set(list_a)
set_b = set(list_b)
print(set_a.intersection(set_b))

[[ 6 49 13 12]
 [34  7 35 26]
 [ 7 24 30 30]
 [ 7  7  5 28]]
[[36 48 23 38]
 [29 19 19 36]
 [49 18  5  7]
 [ 9 28 24 13]]
{5, 7, 13, 49, 24, 28}


In [64]:
a=np.random.randint(1,10,(4,4))
b=np.random.randint(1,10,(4,4))
print(a)
print(b)
print(np.intersect1d(a,b))

[[1 8 4 8]
 [9 6 6 8]
 [3 6 8 9]
 [4 4 9 3]]
[[6 4 8 9]
 [2 5 6 5]
 [3 6 8 8]
 [6 8 7 5]]
[3 4 6 8 9]


### 14. Consider a generator function that generates 10 integers and use it to build an array
Level: Medium

In [65]:
def generator():
    for num in range(1,11):
        yield num
a=np.fromiter(generator(),dtype=float)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


### 15. Subtract the mean of each row of a matrix
Level: Hard

### 16. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? 
Level: Hard

### 17. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.
Level: Hard

In [66]:
def generator():
    for i in range(5,51,5):
        yield i
arr=np.fromiter(generator(),dtype=float)
print(arr)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]
