# NumPy Graded Test 1
<hr>


In [1]:
import numpy as np

### 1. Count The Number Of Times Each Value Appears In An Array Of Integers

In [12]:
a = np.random.randint(1,10,20)
print(a)
np. count_nonzero(a==2)

[9 7 2 9 4 8 3 6 5 6 1 3 3 1 7 1 8 3 9 8]


1

### 2. Given 9 Integers. You have to convert them into 3*3 Numpy array using Reshape function.

In [13]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 3. How to find the memory size of any array 

In [14]:
a = np.arange(9).reshape(3,3)
print("%d bytes" % (a.size * a.itemsize))

36 bytes


### 4. Create a 2d array of size 10 by 10 with 1 on the border and 0 inside.

In [20]:
a = np.ones((10,10))
a[1:-1, 1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 5.Create a 8x8 matrix and fill it with a checkerboard pattern.

In [23]:
x = np.zeros((n, n), dtype = int) 
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print("Checkerboard pattern:") 
print(x)


Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 6. Normalize a 5x5 random matrix.

normalization formula : ((a-mean(a))/std(a))

In [26]:
a = np.random.randint(1,50,(5,5))
print((a-np.mean(a))/np.std(a))

[[-0.37516348  0.03262291  0.6443025  -1.39462947  0.7122669 ]
 [-0.78294988 -0.23923468  1.52783969  1.73173289  1.66376849]
 [ 0.03262291 -1.25870067  1.66376849 -0.85091428 -0.91887867]
 [-0.98684307 -1.46259387  0.5083737   0.5083737  -0.51109228]
 [-0.10330589  1.45987529 -0.23923468 -0.30719908 -1.05480747]]


### 7. Given a 1D array in range(0,11), negate all elements which are between 3 and 8, in place.

In [56]:
a = np.arange(11)
print(np.negative(a[3:9]))
print(a)

[-3 -4 -5 -6 -7 -8]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [59]:
a=np.arange(11)
a
m = (a > 3) & (a < 8)
a[m] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


### 8. How to get the dates of yesterday, today and tomorrow? 

In [35]:
print(np.datetime64('today', 'D') - np.timedelta64(1, 'D') )
print(np.datetime64('today', 'D'))
print(np.datetime64('today', 'D') + np.timedelta64(1, 'D') )

2020-02-13
2020-02-14
2020-02-15


### 9. Generate two arrays of size 2X4 & 3X3, find difference between them. 

In [39]:
a = np.random.randint(1,100,(2,4))
b = np.random.randint(1,100,(3,3))

a.reshape(1,2,1,4)-b.reshape(3,1,3,1)

array([[[[ 39,  26,  28,  46],
         [ 23,  10,  12,  30],
         [ 14,   1,   3,  21]],

        [[  9,  30,  -9,   5],
         [ -7,  14, -25, -11],
         [-16,   5, -34, -20]]],


       [[[-13, -26, -24,  -6],
         [ 49,  36,  38,  56],
         [-17, -30, -28, -10]],

        [[-43, -22, -61, -47],
         [ 19,  40,   1,  15],
         [-47, -26, -65, -51]]],


       [[[-21, -34, -32, -14],
         [ 68,  55,  57,  75],
         [ 19,   6,   8,  26]],

        [[-51, -30, -69, -55],
         [ 38,  59,  20,  34],
         [-11,  10, -29, -15]]]])

### 10. Given 1d array of ['cat','dog','rat'], genrate 100 elements of 1d array consisting of the above 3 value ?
['cat','cat',...,'rat','dog','dog','cat'...]

In [42]:

np.choose(np.random.randint(0,3,100),choices = ["cat","dog","rat"])


array(['rat', 'dog', 'dog', 'rat', 'rat', 'cat', 'dog', 'dog', 'rat',
       'dog', 'cat', 'rat', 'dog', 'cat', 'cat', 'rat', 'dog', 'cat',
       'cat', 'rat', 'rat', 'cat', 'dog', 'cat', 'cat', 'dog', 'rat',
       'dog', 'rat', 'cat', 'rat', 'rat', 'cat', 'dog', 'dog', 'cat',
       'cat', 'rat', 'rat', 'dog', 'dog', 'dog', 'cat', 'cat', 'rat',
       'rat', 'cat', 'cat', 'cat', 'cat', 'cat', 'cat', 'cat', 'dog',
       'rat', 'cat', 'rat', 'dog', 'dog', 'rat', 'cat', 'rat', 'rat',
       'cat', 'rat', 'rat', 'rat', 'rat', 'cat', 'cat', 'dog', 'dog',
       'rat', 'cat', 'rat', 'dog', 'cat', 'rat', 'rat', 'dog', 'rat',
       'dog', 'dog', 'dog', 'cat', 'rat', 'cat', 'rat', 'cat', 'dog',
       'cat', 'dog', 'dog', 'cat', 'cat', 'rat', 'rat', 'dog', 'dog',
       'cat'], dtype='<U3')

### 11. Create a vector of size 10 with values ranging from 0 to 1, both excluded without manually deducing the values

In [44]:
v = np.linspace(0,1,10)
v

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

### 12. Given a two dimensional array, how to extract unique rows?

In [49]:
a = np.random.randint(1,10,(6,4))
print(a)
np.unique(a,axis =0)

[[1 6 2 7]
 [8 9 4 8]
 [2 4 6 6]
 [8 3 9 7]
 [3 4 2 3]
 [9 6 6 1]]


array([[1, 6, 2, 7],
       [2, 4, 6, 6],
       [3, 4, 2, 3],
       [8, 3, 9, 7],
       [8, 9, 4, 8],
       [9, 6, 6, 1]])

### 13. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area.

In [ ]:
a = np.random.randint(0,1)

### 14. How to find the closest value (to a given scalar) in a vector? 

In [67]:
array = np.random.randint(1,10,(6,4))
print(array)
def find_nearest(array, value):
    array = np.asarray(array)
    idx = (np.abs(array - value)).argmin()
    return array[idx]

array = np.random.random(10)
print(array)

value = 0.5

print("nearestvalue :",find_nearest(array, value))

[[6 9 2 5]
 [8 5 1 4]
 [8 9 8 9]
 [3 7 6 4]
 [9 3 7 2]
 [1 1 3 2]]
[0.08564058 0.27318328 0.13836173 0.56686822 0.968528   0.17682231
 0.37369132 0.20762493 0.75957167 0.64889103]
nearestvalue : 0.5668682221588286


### 15. Consider a random vector with shape (10,2) representing coordinates, find point by point distances. Use euclidian distance.

In [199]:
array = np.random.randint(1,100,(10,2))
print(array)

for value in range(len(array)-1):
    dist = np.linalg.norm(array[value] - array[value+1])
    print("distance between {} and {} is".format(array[value],array[value+1]),np.round(dist,2))
    

[[35 16]
 [20 13]
 [40 14]
 [90 26]
 [43 45]
 [27 47]
 [95 72]
 [12  8]
 [39 18]
 [63  5]]
distance between [35 16] and [20 13] is 15.3
distance between [20 13] and [40 14] is 20.02
distance between [40 14] and [90 26] is 51.42
distance between [90 26] and [43 45] is 50.7
distance between [43 45] and [27 47] is 16.12
distance between [27 47] and [95 72] is 72.45
distance between [95 72] and [12  8] is 104.81
distance between [12  8] and [39 18] is 28.79
distance between [39 18] and [63  5] is 27.29


### 16. How to sort an array by the nth column? 

In [198]:
array = np.random.randint(1,100,(4,6))
print(array)
n = 5
sorted_array = array[np.argsort(array[:, n])]
print("---------------------------------------------")
print(sorted_array)


[[14 46 69 35 83 20]
 [72 49 20 57 93 45]
 [63 45 95 49 38 34]
 [58 43 94 90 28 34]]
---------------------------------------------
[[14 46 69 35 83 20]
 [63 45 95 49 38 34]
 [58 43 94 90 28 34]
 [72 49 20 57 93 45]]


### 17.How to tell if a given 2D array has null columns? 

In [169]:
array = np.array([[2,22,0],[-11,33,0],[13,872,0]])
print(array)
np.any(array,axis =0)

[[  2  22   0]
 [-11  33   0]
 [ 13 872   0]]


array([ True,  True, False])

### 18. Considering a two dimensions array, how to get sum over the last two columns at once?

In [153]:
array = np.random.randint(1,100,(4,6))
print(array)
sum_array= np.sum(array,axis=0)
print("sum of last two columns:",sum_array[-1] + sum_array[-2])

[[22 38 13  9 71 98]
 [19 59 60 71 30  2]
 [72 83 47 64 69 34]
 [87 55 57 38 84 72]]
sum of last two columns: 460


### 19. Given a 2d array of 5X5, increment 1st column by 1, second column by 2, 3rd column by 3 & so on till the last column

In [196]:
array = np.random.randint(1,100,(5,5))
print(array)
print("-----------------------")
array[:,0] = array[:,0] +1
array[:,1] = array[:,1] +2
array[:,2] = array[:,2] +3
array[:,3] = array[:,3] +4
array[:,4] = array[:,4] +5
print("-----------------------")
print(array)

[[84 73 65 37 25]
 [34 23 44 58 42]
 [47 28 63 54 46]
 [74 70 68 28 16]
 [62 88 45 10  8]]
-----------------------
-----------------------
[[85 75 68 41 30]
 [35 25 47 62 47]
 [48 30 66 58 51]
 [75 72 71 32 21]
 [63 90 48 14 13]]


### 20. Given a 1d array(size 100) of boolean values, identify total number of True in it. 

In [118]:
array = np.random.randint(0,2,100)
print(array)
np.count_nonzero(array)

[0 0 1 1 1 1 1 0 0 1 1 0 1 1 1 0 0 0 0 0 0 0 1 1 1 1 0 0 1 0 0 0 1 0 1 1 1
 0 1 0 0 0 1 0 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 1 0 1 1 1 0 0 0 1 1 0 0 0 1 0
 0 1 0 1 1 0 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 0 1 0 1 0]


49

### 21. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? 

### 22. How to swap two rows of an array?

In [112]:
a = np.array([[4,3,1], [5,7,0], [9,9,3], [8,2,4]])
print(a) 
print("-----------------------------------")
# swapping 1st and 3rd rows
a[[0, 2]] = a[[2, 0]]
print(a)


[[4 3 1]
 [5 7 0]
 [9 9 3]
 [8 2 4]]
-----------------------------------
[[9 9 3]
 [5 7 0]
 [4 3 1]
 [8 2 4]]


### 24. How to get n largest value of an array?

In [143]:
array = np.random.randint(1,100,10)
print(array)
sorted_index = np.argsort(array)
n =5
print(sorted_index)
ind =sorted_index[-n]
print(array[ind])

[36 95 53 50 28 13 29 14  1 70]
[8 5 7 4 6 0 3 2 9 1]
36


### 25.  Given two random arrays of shape 5X5, identify the common elements between them.

In [129]:
a = np.random.randint(0,100,(5,5))
b = np.random.randint(0,100,(5,5))
print(a)
print(b)
np.intersect1d(a,b)

[[13 59 77 71 20]
 [98 60 56 35  0]
 [29 55 68 99 36]
 [81 67 10 10 16]
 [60 41 72 82 65]]
[[14 68 33 10 43]
 [42 26 29 96 64]
 [46 53 72 23 97]
 [32 63 12  3  3]
 [61 27 73 92  3]]


array([10, 29, 68, 72])

### 26. How to get index of top two highest value in a 1d array?
[2,22,11,-11,33,7,13,872,-23]

In [197]:
a = np.array([2,22,11,-11,33,7,13,872,-23])
print(a)
b = np.argsort(a)
print(b)
print("second highest element index:",b[-2])

[  2  22  11 -11  33   7  13 872 -23]
[8 3 0 5 2 6 1 4 7]
second highest element index: 4
